{
 "title": "Autoria Stats",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "brand",
    "label": "Brand",
    "query": "SELECT DISTINCT(brand) FROM autoria;"
   },
   {
    "name": "model",
    "label": "Model",
    "query": "SELECT DISTINCT(model) FROM autoria WHERE brand LIKE any(array[${brand:sqlstring}]);"
   },
   {
    "name": "gear",
    "label": "Gear",
    "query": "SELECT DISTINCT(gear) FROM autoria;"
   },
   { "name": "year_min", "label": "Year Min", "query": "1900" },
   { "name": "year_max", "label": "Year Max", "query": "2024" },
   { "name": "min_mileage", "label": "Min mileage", "query": "0" },
   { "name": "max_mileage", "label": "Max Mileage", "query": "999" },
   {
    "name": "fuel",
    "label": "Fuel",
    "query": "SELECT DISTINCT(fuel) FROM autoria;"
   },
   {
    "name": "engine",
    "label": "Engine",
    "query": "SELECT DISTINCT(engine)\nFROM autoria\nWHERE brand LIKE any(array[${brand:sqlstring}])\n  AND model LIKE any(array[${model:sqlstring}])\n  AND year BETWEEN ${year_min:raw} AND ${year_max:raw}\n  AND fuel LIKE any(array[${fuel:sqlstring}])\n  AND gear LIKE any(array[${gear:sqlstring}]) "
   },
   {
    "name": "generation",
    "label": "Generation",
    "query": "SELECT DISTINCT(generation) FROM autoria WHERE brand LIKE any(array[${brand:sqlstring}]) AND model LIKE any(array[${model:sqlstring}]) AND year BETWEEN ${year_min:raw} AND ${year_max:raw} AND fuel LIKE any(array[${fuel:sqlstring}]) AND gear LIKE any(array[${gear:sqlstring}]) AND engine LIKE any(array[${engine:sqlstring}]);"
   },
   {
    "name": "equipment",
    "label": "Equip",
    "query": "SELECT DISTINCT(equipment)\nFROM autoria\nWHERE brand LIKE any(array[${brand:sqlstring}])\n  AND model LIKE any(array[${model:sqlstring}])\n  AND year BETWEEN ${year_min:raw} AND ${year_max:raw}\n  AND fuel LIKE any(array[${fuel:sqlstring}])\n  AND generation LIKE any(array[${generation:sqlstring}])\n  AND gear LIKE any(array[${gear:sqlstring}])\n  AND engine LIKE any(array[${engine:sqlstring}])"
   },
   {
    "name": "modification",
    "label": "Modification",
    "query": "SELECT DISTINCT(equipment) FROM autoria WHERE brand LIKE any(array[${brand:sqlstring}]) AND model LIKE any(array[${model:sqlstring}]);"
   },
   { "name": "price_min", "label": "Price Min", "query": "0" },
   { "name": "price_max", "label": "Price Max", "query": "999999" },
   { "name": "cars_count", "label": "Cars", "query": "0" }
  ]
 },
 "panels": [
  { "title": "AutoRia stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Price distribution",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "rawSql": "SELECT CAST(CAST(price AS FLOAT)/1000 AS INT) * 1000 as price, COUNT(id) as cars \n      FROM autoria \n      WHERE year BETWEEN ${year_min:raw} AND ${year_max:raw} \n      AND price BETWEEN ${price_min:raw} AND ${price_max:raw}\n      AND brand LIKE any(array[${brand:sqlstring}])\n      AND model LIKE any(array[${model:sqlstring}])\n      GROUP BY CAST(CAST(price AS FLOAT)/1000 AS INT) * 1000  \n      ORDER BY CAST(CAST(price AS FLOAT)/1000 AS INT) * 1000 asc;"
    }
   ]
  },
  {
   "title": "Distribution by brand/model/year",
   "type": "table",
   "gridPos": { "h": 16, "w": 5, "x": 8, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT format('%s %s (%s)', brand, model, year) as name, count(id) as cars, AVG(price) as \"Avg. Price\" FROM autoria \n  WHERE brand LIKE any(array[${brand:sqlstring}])\n        AND model LIKE any(array[${model:sqlstring}])\n        AND year BETWEEN ${year_min:raw} AND ${year_max:raw}\n        AND mileage BETWEEN ${min_mileage:raw} AND ${max_mileage:raw}\n        AND gear LIKE any(array[${gear:sqlstring}])\n        AND fuel LIKE any(array[${fuel:sqlstring}])\n  GROUP BY model, brand, year \n  HAVING \n      AVG(price) BETWEEN ${price_min:raw} AND ${price_max:raw}\n      AND COUNT(id) >= ${cars_count:raw}\n  ORDER BY cars DESC;"
    }
   ]
  },
  {
   "title": "Distribution by brand/model/gen",
   "type": "table",
   "gridPos": { "h": 16, "w": 6, "x": 13, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT format('%s %s [%s] (%s-%s)', brand, model, generation, MIN(year), MAX(year)) as name, count(id) as cars, AVG(price) as \"Avg. Price\" FROM autoria \n  WHERE brand LIKE any(array[${brand:sqlstring}])\n        AND model LIKE any(array[${model:sqlstring}])\n        AND year BETWEEN ${year_min:raw} AND ${year_max:raw}\n        AND mileage BETWEEN ${min_mileage:raw} AND ${max_mileage:raw}\n        AND gear LIKE any(array[${gear:sqlstring}])\n        AND fuel LIKE any(array[${fuel:sqlstring}])\n  GROUP BY model, brand, generation \n  HAVING \n      AVG(price) BETWEEN ${price_min:raw} AND ${price_max:raw}\n      AND COUNT(id) >= ${cars_count:raw}\n  ORDER BY cars DESC;"
    }
   ]
  },
  {
   "title": "Distribution by area",
   "type": "table",
   "gridPos": { "h": 16, "w": 4, "x": 19, "y": 1 },
   "targets": [
    {
     "rawSql": "SELECT city, count(id) as cars, AVG(price) as \"Avg. Price\" FROM autoria \n  WHERE brand LIKE any(array[${brand:sqlstring}])\n        AND model LIKE any(array[${model:sqlstring}])\n        AND year BETWEEN ${year_min:raw} AND ${year_max:raw}\n  GROUP BY city\n  HAVING AVG(price) BETWEEN ${price_min:raw} AND ${price_max:raw}\n  ORDER BY cars DESC;"
    }
   ]
  },
  {
   "title": "Year distribution",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 9 },
   "targets": [
    {
     "rawSql": "SELECT year, COUNT(id) as cars FROM autoria \nWHERE year BETWEEN ${year_min:raw} AND ${year_max:raw} \nAND price BETWEEN ${price_min:raw} AND ${price_max:raw}\nAND brand LIKE any(array[${brand:sqlstring}])\nAND model LIKE any(array[${model:sqlstring}])\nGROUP BY year ORDER BY year asc;"
    }
   ]
  },
  {
   "title": "Car stat",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cars",
     "type": "stat",
     "gridPos": { "h": 6, "w": 2, "x": 0, "y": 18 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT COUNT(id) FROM autoria WHERE \n                                brand LIKE any(array[${brand:sqlstring}]) \n                                AND model LIKE any(array[${model:sqlstring}]) \n                                AND year BETWEEN ${year_min:raw} AND ${year_max:raw} \n                                AND mileage BETWEEN ${min_mileage:raw} AND ${max_mileage:raw} \n                                AND fuel LIKE any(array[${fuel:sqlstring}]) \n                                AND generation LIKE any(array[${generation:sqlstring}]) \n                                AND gear LIKE any(array[${gear:sqlstring}]) \n                                AND engine LIKE any(array[${engine:sqlstring}]) \n                                AND equipment LIKE any(array[${equipment:sqlstring}]) \n                                AND modification LIKE any(array[${modification:sqlstring}])"
      }
     ]
    },
    {
     "title": "Min Price ($)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 2, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "rawSql": "SELECT MIN(price) FROM autoria WHERE \n                                brand LIKE any(array[${brand:sqlstring}]) \n                                AND model LIKE any(array[${model:sqlstring}]) \n                                AND year BETWEEN ${year_min:raw} AND ${year_max:raw} \n                                AND mileage BETWEEN ${min_mileage:raw} AND ${max_mileage:raw} \n                                AND fuel LIKE any(array[${fuel:sqlstring}]) \n                                AND generation LIKE any(array[${generation:sqlstring}]) \n                                AND gear LIKE any(array[${gear:sqlstring}]) \n                                AND engine LIKE any(array[${engine:sqlstring}]) \n                                AND equipment LIKE any(array[${equipment:sqlstring}]) \n                                AND modification LIKE any(array[${modification:sqlstring}])"
      }
     ]
    },
    {
     "title": "Average Price ($)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 4, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT AVG(price) FROM autoria WHERE \n                                brand LIKE any(array[${brand:sqlstring}]) \n                                AND model LIKE any(array[${model:sqlstring}]) \n                                AND year BETWEEN ${year_min:raw} AND ${year_max:raw} \n                                AND mileage BETWEEN ${min_mileage:raw} AND ${max_mileage:raw} \n                                AND fuel LIKE any(array[${fuel:sqlstring}]) \n                                AND generation LIKE any(array[${generation:sqlstring}]) \n                                AND gear LIKE any(array[${gear:sqlstring}]) \n                                AND engine LIKE any(array[${engine:sqlstring}]) \n                                AND equipment LIKE any(array[${equipment:sqlstring}]) \n                                AND modification LIKE any(array[${modification:sqlstring}])"
      }
     ]
    },
    {
     "title": "Max Price ($)",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 6, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT MAX(price) FROM autoria WHERE \n                                brand LIKE any(array[${brand:sqlstring}]) \n                                AND model LIKE any(array[${model:sqlstring}]) \n                                AND year BETWEEN ${year_min:raw} AND ${year_max:raw} \n                                AND mileage BETWEEN ${min_mileage:raw} AND ${max_mileage:raw} \n                                AND fuel LIKE any(array[${fuel:sqlstring}]) \n                                AND generation LIKE any(array[${generation:sqlstring}]) \n                                AND gear LIKE any(array[${gear:sqlstring}]) \n                                AND engine LIKE any(array[${engine:sqlstring}]) \n                                AND equipment LIKE any(array[${equipment:sqlstring}]) \n                                AND modification LIKE any(array[${modification:sqlstring}])"
      }
     ]
    },
    {
     "title": "Lots",
     "type": "table",
     "gridPos": { "h": 18, "w": 10, "x": 8, "y": 18 },
     "targets": [
      {
       "rawSql": "SELECT 'https://auto.ria.com/uk' || url as link, engine, gear, year, CAST(mileage AS INT) * 1000 AS mileage, price FROM autoria WHERE \n                                brand LIKE any(array[${brand:sqlstring}]) \n                                AND model LIKE any(array[${model:sqlstring}]) \n                                AND year BETWEEN ${year_min:raw} AND ${year_max:raw} \n                                AND mileage BETWEEN ${min_mileage:raw} AND ${max_mileage:raw} \n                                AND fuel LIKE any(array[${fuel:sqlstring}]) \n                                AND generation LIKE any(array[${generation:sqlstring}]) \n                                AND gear LIKE any(array[${gear:sqlstring}]) \n                                AND engine LIKE any(array[${engine:sqlstring}]) \n                                AND equipment LIKE any(array[${equipment:sqlstring}]) \n                                AND modification LIKE any(array[${modification:sqlstring}])\nORDER BY price ASC;"
      }
     ]
    },
    {
     "title": "Average mileage",
     "type": "stat",
     "gridPos": { "h": 3, "w": 2, "x": 2, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "rawSql": "SELECT AVG(mileage) * 1000 FROM autoria WHERE \n                                brand LIKE any(array[${brand:sqlstring}]) \n                                AND model LIKE any(array[${model:sqlstring}]) \n                                AND year BETWEEN ${year_min:raw} AND ${year_max:raw} \n                                AND mileage BETWEEN ${min_mileage:raw} AND ${max_mileage:raw} \n                                AND fuel LIKE any(array[${fuel:sqlstring}]) \n                                AND generation LIKE any(array[${generation:sqlstring}]) \n                                AND gear LIKE any(array[${gear:sqlstring}]) \n                                AND engine LIKE any(array[${engine:sqlstring}]) \n                                AND equipment LIKE any(array[${equipment:sqlstring}]) \n                                AND modification LIKE any(array[${modification:sqlstring}])"
      }
     ]
    },
    {
     "title": "Mileage distribution",
     "type": "barchart",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "rawSql": "SELECT CAST(mileage/10 AS INT) * 10 as mileage, COUNT(id) FROM autoria WHERE \n                                brand LIKE any(array[${brand:sqlstring}]) \n                                AND model LIKE any(array[${model:sqlstring}]) \n                                AND year BETWEEN ${year_min:raw} AND ${year_max:raw} \n                                AND mileage BETWEEN ${min_mileage:raw} AND ${max_mileage:raw} \n                                AND fuel LIKE any(array[${fuel:sqlstring}]) \n                                AND generation LIKE any(array[${generation:sqlstring}]) \n                                AND gear LIKE any(array[${gear:sqlstring}]) \n                                AND engine LIKE any(array[${engine:sqlstring}]) \n                                AND equipment LIKE any(array[${equipment:sqlstring}]) \n                                AND modification LIKE any(array[${modification:sqlstring}])\n\n GROUP BY CAST(mileage/10 AS INT)*10;"
      }
     ]
    },
    {
     "title": "Price distribution",
     "type": "barchart",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
     "targets": [
      {
       "rawSql": "SELECT CAST(price/100 AS INT) * 100 AS price, count(id) FROM autoria WHERE \n                                brand LIKE any(array[${brand:sqlstring}]) \n                                AND model LIKE any(array[${model:sqlstring}]) \n                                AND year BETWEEN ${year_min:raw} AND ${year_max:raw} \n                                AND mileage BETWEEN ${min_mileage:raw} AND ${max_mileage:raw} \n                                AND fuel LIKE any(array[${fuel:sqlstring}]) \n                                AND generation LIKE any(array[${generation:sqlstring}]) \n                                AND gear LIKE any(array[${gear:sqlstring}]) \n                                AND engine LIKE any(array[${engine:sqlstring}]) \n                                AND equipment LIKE any(array[${equipment:sqlstring}]) \n                                AND modification LIKE any(array[${modification:sqlstring}])\n\n GROUP BY CAST(price/100 AS INT) ORDER BY price;"
      }
     ]
    }
   ]
  }
 ]
}